import React, { createContext, useContext, useEffect, useMemo, useState } from "react";

const LangContext = createContext(null);

const STORE_KEY = "heja_lang";

export const LANGS = {
  en: { code: "en", label: "English", short: "EN", dir: "ltr" },
  ku: { code: "ku", label: "کوردی", short: "KU", dir: "rtl" },
  ar: { code: "ar", label: "العربية", short: "AR", dir: "rtl" },
};

// English-first content with full Kurdish (Sorani) coverage for the Home page.
import { PAGE_TRANSLATIONS } from "../data/translations";
import { PAGE_TRANSLATIONS2 } from "../data/translations2";
import { PAGE_TRANSLATIONS3 } from "../data/translations3";
import { PAGE_TRANSLATIONS4 } from "../data/translations4";

const TRANSLATIONS = {
...PAGE_TRANSLATIONS,
...PAGE_TRANSLATIONS2,
...PAGE_TRANSLATIONS3,
...PAGE_TRANSLATIONS4,
  // ===== Legal disclaimers (existing) =====
  footerDisclaimer: {
    en: "Hêja is a data aggregation tool. All information is provided for educational reference only. We do not perform chemical testing. We are not a laboratory or regulatory body. Scores are generated by automated algorithms cross-referencing international databases and do not represent professional, medical, or regulatory opinions.", 
    ku: "هێژا ئامرازێکی کۆکردنەوەی داتایە. هەموو زانیاریەکان تەنها بۆ مەبەستی پەروەردەیی دابین دەکرێت. ئێمە تاقیکردنەوەی کیمیایی ناکەین. ئێمە تاقیگە یان دەستەی ڕێکخستن نین. نمرەکان لە لایەن ئەلگۆریتمە ئۆتۆماتیکەکانەوە بە لێکدانەوەی بنکەدراوە نێودەوڵەتییەکان دروست دەکرێن و نوێنەرایەتی ڕای پیشەیی، پزیشکی، یان ڕێکخستن ناکەن.", 
    ar: "هيجا هي أداة لتجميع البيانات. يتم توفير جميع المعلومات كمرجع تعليمي فقط. نحن لا نجري اختبارات كيميائية، ولسنا مختبراً أو هيئة تنظيمية. يتم إنشاء الدرجات بواسطة خوارزميات مؤتمتة تقارن بقواعد البيانات الدولية ولا تمثل آراء مهنية أو طبية أو تنظيمية.",
  },
  productNotice: {
    en: "This cross-reference is for educational reference only. Not medical advice. Click sources to verify independently.", 
    ku: "ئەم لێکدانەوەیە تەنها بۆ مەبەستی پەروەردەیییە. ئامۆژگاری پزیشکی نییە. کلیک لە سەرچاوەکان بکە بۆ پشتڕاستکردنەوەی سەربەخۆ.", 
    ar: "هذا التقاطع المرجعي للأغراض التعليمية فقط، وليس نصيحة طبية. انقر على المصادر للتحقق بشكل مستقل.",
  },
  aiNotice: {
    en: "Generated by ChatGPT AI. May contain errors. Verify against cited sources.", 
    ku: "ئەم ئەنجامە بە یارمەتی ChatGPT دروست کراوە. لەوانەیە هەڵە تێدا بێت. بە سەرچاوەکان پشتڕاست بکەوە.", 
    ar: "تم الإنشاء بواسطة ChatGPT AI. قد يحتوي على أخطاء. تحقق بناءً على المصادر المذكورة.",
  },

  // ===== HERO =====
  heroEyebrow: {
    en: "Community Research · Kurdistan", ku: "توێژینەوەی کۆمەڵگا · کوردستان", ar: "بحث مجتمعي · كردستان",
  },
  heroTitleLine1: { en: "Know What Research", ku: "بزانە توێژینەوە", ar: "اعرف ماذا تقول الأبحاث" },
  heroTitleHighlight: { en: "Says About", ku: "چی دەڵێت دەربارەی", ar: "عن" },
  heroTitleTail: { en: "Your Products", ku: "بەرهەمەکانت", ar: "منتجاتك" },
  heroSubtitle: {
    en: "Hêja cross-references ingredients from Kurdistan market products against international scientific databases — so you and your family can make informed decisions.", 
    ku: "هێژا پێکهاتەکانی بەرهەمەکانی بازاڕی کوردستان بە بنکەدراوە زانستییە نێودەوڵەتییەکان لێک دەکاتەوە — تاکو تۆ و خێزانەکەت بتوانن بڕیاری ئاگادارانە بدەن.", 
    ar: "تقوم منصة هيجا بمطابقة مكونات منتجات أسواق كردستان مع قواعد البيانات العلمية الدولية — لكي تتمكن أنت وعائلتك من اتخاذ قرارات مبنية على المعرفة.",
  },
  heroScrollHint: { en: "Scroll to explore", ku: "سکرۆڵ بکە بۆ گەڕان", ar: "قم بالتمرير للاستكشاف" },

  // ===== Notify form =====
  notifyPlaceholder: {
    en: "Enter your email for app launch notification", ku: "ئیمەیڵەکەت بنووسە بۆ ئاگاداری دەستپێکردنی ئەپ", ar: "أدخل بريدك الإلكتروني لإشعار إطلاق التطبيق",
  },
  notifyBtn: { en: "Get Notified", ku: "ئاگادار ببە", ar: "أعلمني" },
  notifySending: { en: "Sending...", ku: "دەنێردرێت...", ar: "جاري الإرسال..." },
  notifyFinePrint: {
    en: "No spam. Unsubscribe anytime. Your data is never sold.", ku: "هیچ سپام نییە. هەر کاتێک بتەوێت واز بهێنە. داتاکەت هەرگیز نافرۆشرێت.", ar: "لا توجد رسائل مزعجة (سبام). يمكنك الإلغاء في أي وقت. لن يتم بيع بياناتك أبداً.",
  },
  notifySuccess: {
    en: "You're on the list. We'll notify you at launch.", ku: "ناوت لە لیستەکەدایە. لە کاتی دەستپێکردندا ئاگادارت دەکەینەوە.", ar: "أسُمك في القائمة. سنعلمك عند الإطلاق.",
  },
  notifyInvalid: { en: "Please enter a valid email.", ku: "تکایە ئیمەیڵێکی دروست بنووسە.", ar: "يرجى إدخال بريد إلكتروني صالح." },
  notifyError: {
    en: "Something went wrong. Please try again.", ku: "هەڵەیەک ڕوویدا. تکایە دووبارە هەوڵ بدەرەوە.", ar: "حدث خطأ ما. يرجى المحاولة مرة أخرى." },

  // ===== STATS =====
  statProductsLabel: { en: "Products Cross-Referenced", ku: "بەرهەمی لێکدراوەتەوە", ar: "منتجات تمت مطابقتها" },
  statDatabasesLabel: { en: "International Databases", ku: "بنکەدراوەی نێودەوڵەتی", ar: "قواعد بيانات دولية" },
  statFreeLabel: { en: "Free. Always.", ku: "بەخۆڕایی. هەمیشە.", ar: "مجاني. دائماً." },
  statLawPrefix: { en: "Law", ku: "یاسا", ar: "قانون" },
  statLawLabel: { en: "Consumer Protection Compliant", ku: "گونجاو لەگەڵ یاسای پاراستنی بەکاربەر", ar: "متوافق مع حماية المستهلك" },

  // ===== FEATURES =====
  featEyebrow: { en: "Mission", ku: "ئەرک", ar: "المهمة" },
  featTitle: { en: "How Hêja Protects Your Family", ku: "هێژا چۆن خێزانەکەت دەپارێزێت", ar: "كيف يحمي هيجا عائلتك" },
  featSubtitle: {
    en: "Six pillars built on independent research, transparent algorithms, and community trust.", ku: "شەش کۆڵەکە بنیاتنراون لەسەر توێژینەوەی سەربەخۆ، ئەلگۆریتمی ڕوون، و متمانەی کۆمەڵگا.", ar: "ستة ركائز مبنية على أبحاث مستقلة، وخوارزميات شفافة، وثقة مجتمعية." },

  feat1Title: { en: "Label Reading", ku: "خوێندنەوەی لەیبڵ", ar: "قراءة الملصقات" },
  feat1Text: {
    en: "We read ingredient labels from products sold in Kurdistan markets and identify every substance listed.", ku: "ئێمە لەیبڵی پێکهاتەکانی ئەو بەرهەمانە دەخوێنینەوە کە لە بازاڕەکانی کوردستان دەفرۆشرێن و هەموو ماددەیەکی ناولیستراو دیاری دەکەین.", ar: "نقرأ ملصقات المكونات من المنتجات التي تباع في أسواق كردستان ونحدد كل مادة مكتوبة." },
  feat2Title: { en: "Database Cross-Reference", ku: "لێکدانەوەی بنکەدراوە", ar: "مطابقة قواعد البيانات" },
  feat2Text: {
    en: "We search Open Food Facts, Noon Iraq Database, ECHA, IARC, CosIng, and Codex Alimentarius for every ingredient found.", ku: "ئێمە لە Open Food Facts، بنکەدراوەی نوون عێراق، ECHA، IARC، CosIng، و Codex Alimentarius دەگەڕێین بۆ هەر پێکهاتەیەک کە دەدۆزرێتەوە.", ar: "نحن نبحث في Open Food Facts و قاعدة بيانات نون في العراق و ECHA و IARC و CosIng و Codex Alimentarius لكل مكون تم العثور عليه." },
  feat3Title: { en: "Transparency Index", ku: "پێوەری ڕوونی", ar: "مؤشر الشفافية" },
  feat3Text: {
    en: "Each product receives a score from 0 to 100 calculated mathematically by cross-referencing flagged versus unflagged ingredients in official databases.", ku: "هەر بەرهەمێک نمرەیەک لە ٠ بۆ ١٠٠ وەردەگرێت کە بە شێوەی بیرکاری ژمێردراوە بە لێکدانەوەی پێکهاتە ئاماژەپێکراوەکان بەرامبەر بە ئەوانەی ئاماژەیان پێنەکراوە لە بنکەدراوە فەرمییەکاندا.", ar: "يتلقى كل منتج درجة من 0 إلى 100 تُحسب رياضياً عن طريق إسناد المكونات التي تم وضع علامة عليها مقابل المكونات غير الموسومة في قواعد البيانات الرسمية." },
  feat4Title: { en: "Every Claim Is Cited", ku: "هەر گوتەیەک سەرچاوەی هەیە", ar: "يتم الاستشهاد بكل إدعاء" },
  feat4Text: {
    en: "Every research flag links directly to the original scientific paper or regulatory database entry. You verify everything independently.", ku: "هەر ئاماژەیەکی توێژینەوە ڕاستەوخۆ لینک دەدات بۆ توێژینەوەی زانستی ڕەسەن یان تۆماری بنکەدراوەی ڕێکخستن. تۆ خۆت هەموو شتێک بە سەربەخۆیی پشتڕاست دەکەیتەوە.", ar: "ترتبط كل شارة بحث بشكل مباشر بالورقة العلمية الأصلية أو قاعدة بيانات تنظيمية. لتتحقق من كل شيء بشكل مستقل." },
  feat5Title: { en: "Kurdistan Market Focus", ku: "سەرنج لەسەر بازاڕی کوردستان", ar: "التركيز على أسواق كردستان" },
  feat5Text: {
    en: "We analyze products actually sold in Kurdistan markets — not just products from Western countries that global apps already cover.", ku: "ئێمە ئەو بەرهەمانە شی دەکەینەوە کە بەڕاستی لە بازاڕەکانی کوردستاندا دەفرۆشرێن — نەک تەنها بەرهەمی وڵاتانی ڕۆژئاوا کە ئەپە جیهانییەکان پێشتر داپۆشیویانە.", ar: "نحن نحلل المنتجات التي تباع فعلياً في أسواق كردستان — وليس فقط المنتجات من الدول الغربية التي تغطيها التطبيقات العالمية بالفعل." },
  feat6Title: { en: "Always Free", ku: "هەمیشە بەخۆڕایی", ar: "مجاني دائماً" },
  feat6Text: {
    en: "No subscriptions. No premium tier. No hidden costs. Health research should be accessible to every family.", ku: "هیچ بەشداربوونێک نییە. هیچ ئاستێکی تایبەتی نییە. هیچ تێچوونێکی شاراوە نییە. توێژینەوەی تەندروستی دەبێت بۆ هەر خێزانێک بەردەست بێت.", ar: "لا يوجد اشتراكات. لا نسخة مدفوعة. لا تكاليف خفية. الأبحاث الصحية يجب أن تكون بمتناول كل أسرة." },

  // ===== STEPS =====
  stepsEyebrow: { en: "Workflow", ku: "ڕێڕەوی کار", ar: "طريقة العمل" },
  stepsTitle: { en: "Five Steps to Informed Decisions", ku: "پێنج هەنگاو بۆ بڕیاری ئاگادارانە", ar: "خمس خطوات لاتخاذ قرارات مدروسة" },
  stepLabel: { en: "STEP", ku: "هەنگاو", ar: "خطوة" },
  step1: {
    en: "Find a product in any Kurdistan market.", ku: "بەرهەمێک لە هەر بازاڕێکی کوردستاندا بدۆزەرەوە.", ar: "إيجاد منتج في أي سوق بكردستان." },
  step2: {
    en: "Search it in Hêja or scan its barcode.", ku: "لە هێژادا بگەڕێ بۆی یان بارکۆدەکەی سکان بکە.", ar: "البحث عنه في هيجا أو إجراء مسح للباركود." },
  step3: {
    en: "See which ingredients appear in international scientific databases — with direct citations.", ku: "ببینە کام پێکهاتە لە بنکەدراوە زانستییە نێودەوڵەتییەکاندا دەردەکەوێت — لەگەڵ سەرچاوەی ڕاستەوخۆ.", ar: "رؤية المكونات التي تظهر في قواعد البيانات العلمية الدولية — مع الإسناد المباشر." },
  step4: {
    en: "Click any flagged ingredient to read the original research.", ku: "کلیک لە هەر پێکهاتەیەکی ئاماژەپێکراو بکە بۆ خوێندنەوەی توێژینەوەی ڕەسەن.", ar: "النقر على أي مكون مشار إليه لقراءة البحث الأصلي الذي يخصّه." },
  step5: {
    en: "Make your own informed decision for your family.", ku: "بڕیاری ئاگادارانەی خۆت بۆ خێزانەکەت بدە.", ar: "اتخاذ القرار المدروس من أجل أسرتك." },

  // ===== SOURCES =====
  sourcesEyebrow: { en: "Foundation", ku: "بناغە", ar: "الأساسيات" },
  sourcesTitle: { en: "Our Scientific Foundation", ku: "بناغەی زانستیمان", ar: "أساسياتنا العلمية" },
  sourcesSubtitle: {
    en: "We never make unsourced claims. Every flag traces back to one of these official international bodies.", ku: "ئێمە هەرگیز گوتەی بێ سەرچاوە ناکەین. هەر ئاماژەیەک دەگەڕێتەوە بۆ یەکێک لەم دەستە فەرمییە نێودەوڵەتییانە.", ar: "نحن لا ندعي أبداً أي ادعاء مجهول المصدر. كل علامة ترجع إلى واحدة من هذه الهيئات الدولية الرسمية." },
  sourcesImportantNotice: {
    en: "Hêja is a data aggregation tool. We do not perform chemical testing. We are not a laboratory or regulatory body. We are a digital search engine that reads labels and searches ingredient names in international scientific databases. All information is provided for educational reference only and does not constitute medical, legal, or regulatory advice.", 
    ku: "هێژا ئامرازێکی کۆکردنەوەی داتایە. ئێمە تاقیکردنەوەی کیمیایی ناکەین. ئێمە تاقیگە یان دەستەی ڕێکخستن نین. ئێمە بزوێنەرێکی گەڕانی دیجیتاڵین کە لەیبڵەکان دەخوێنینەوە و ناوی پێکهاتەکان لە بنکەدراوە زانستییە نێودەوڵەتییەکاندا دەگەڕێین. هەموو زانیاریەکان تەنها بۆ سەرچاوەی پەروەردەیی پێشکەش دەکرێن و ئامۆژگاری پزیشکی، یاسایی، یان ڕێکخستن نین.", 
    ar: "إن هيجا أداة تجميع بيانات. نحن لا نقم بأي اختبارات كيميائية، ولسنا مختبراً أو هيئة تنظيمية. نحن مجرد محرك بحث رقمي يقرأ الملصقات ويبحث في أسماء المكونات ضمن قواعد البيانات العلمية الدولية. جميع المعلومات المتوفرة تم تقديمها كمرجع تعليمي فقط، ولا تشكل أي نصيحة طبية أو قانونية أو تنظيمية." },

  // ===== SCIENTIFIC SOURCE CARDS (names + short blurbs) =====
  "source.ECHA.name": {
    en: "European Chemicals Agency", ku: "دەستەی ئەورووپی بۆ کیمیاییەکان", ar: "الوكالة الأوروبية للمواد الكيميائية",
  },
  "source.ECHA.short": {
    en: "Official EU database of chemical substance classifications.", ku: "بنکەدراوەی فەرمی یەکێتی ئەورووپا بۆ پۆلێنکردنی ماددە کیمیاییەکان.", ar: "قاعدة البيانات الرسمية للاتحاد الأوروبي لتصنيفات المواد الكيميائية.",
  },
  "source.IARC.name": {
    en: "International Agency for Research on Cancer", ku: "دەستەی نێودەوڵەتی بۆ توێژینەوەی شێرپەنجە", ar: "الوكالة الدولية لأبحاث السرطان",
  },
  "source.IARC.short": {
    en: "WHO body evaluating carcinogenic risks to humans.", ku: "دەستەیەکی ڕێکخراوی تەندروستی جیهانییە کە مەترسی شێرپەنجەزایی بۆ مرۆڤ هەڵدەسەنگێنێت.", ar: "هيئة تابعة لمنظمة الصحة العالمية لتقييم المخاطر المسرطنة على البشر.",
  },
  "source.CosIng.name": {
    en: "European Commission Cosmetic Ingredients Database", ku: "بنکەدراوەی پێکهاتەی جوانکاری کۆمیسیۆنی ئەورووپا", ar: "قاعدة بيانات مكونات مستحضرات التجميل بالمفوضية الأوروبية",
  },
  "source.CosIng.short": {
    en: "European Commission database of cosmetic ingredient regulations.", ku: "بنکەدراوەی کۆمیسیۆنی ئەورووپا بۆ ڕێساکانی پێکهاتەی جوانکاری.", ar: "قاعدة بيانات المفوضية الأوروبية لتشريعات مكونات مستحضرات التجميل.",
  },
  "source.Codex Alimentarius.name": {
    en: "International Food Standards", ku: "ستانداردە نێودەوڵەتییەکانی خواردن", ar: "الدستور الغذائي (القياسات العالمية للغذاء)",
  },
  "source.Codex Alimentarius.short": {
    en: "International FAO/WHO food standards program.", ku: "بەرنامەی ستانداردە نێودەوڵەتییەکانی خواردنی FAO/WHO.", ar: "برنامج معايير ومقاييس الأغذية الدولية التابع لمنظمتي الأغذية والزراعة والصحة العالمية.",
  },
  "source.Open Food Facts.name": {
    en: "Open Food Facts Global Ingredient Database", ku: "بنکەدراوەی جیهانی پێکهاتەی Open Food Facts", ar: "قاعدة بيانات مكونات Open Food Facts المفتوحة",
  },
  "source.Open Food Facts.short": {
    en: "Open-source global product ingredient database.", ku: "بنکەدراوەی جیهانی سەرچاوەکراوەی پێکهاتەی بەرهەمەکان.", ar: "قاعدة بيانات عالمية ومفتوحة المصدر لمكونات المنتجات.",
  },
  "source.PubMed.name": {
    en: "National Library of Medicine PubMed Database", ku: "بنکەدراوەی PubMed ی کتێبخانەی نیشتمانی پزیشکی", ar: "قاعدة بيانات المكتبة الوطنية للطب PubMed",
  },
  "source.PubMed.short": {
    en: "World's largest database of peer-reviewed biomedical research.", ku: "گەورەترین بنکەدراوەی جیهان بۆ توێژینەوەی بایۆپزیشکی پێداچوونەوەکراو.", ar: "أكبر قاعدة بيانات في العالم في مجال البحوث الطبية الحيوية المراجعة من قِبل الأقران.",
  },

  // ===== APP COMING SOON =====
  appEyebrow: { en: "Mobile · Android", ku: "مۆبایل · ئەندرۆید", ar: "تطبيق موبايل · أندرويد" },
  appTitle: { en: "Hêja App — Coming to Android", ku: "ئەپی هێژا — بەمزوانە بۆ ئەندرۆید", ar: "تطبيق هيجا — قريباً على أندرويد" },
  appSubtitle: {
    en: "Scan barcodes and analyze ingredients directly from your phone. Currently in development.", ku: "بارکۆدەکان سکان بکە و پێکهاتەکان ڕاستەوخۆ لە مۆبایلەکەتەوە شی بکەرەوە. ئێستا لە قۆناغی گەشەپێداندایە.", ar: "قم بمسح الباركود وتحليل المكونات مباشرة من هاتفك، نقم بالتطوير والعمل عليه حالياً." },
  appComingSoon: { en: "Coming Soon", ku: "بەمزوانە دادێت", ar: "قريباً" },
  appGooglePlay: { en: "Google Play", ku: "گووگڵ پلەی", ar: "جوجل بلاي" },
  appScanBarcode: { en: "SCAN BARCODE", ku: "بارکۆد سکان بکە", ar: "مسح الباركود" },

  // ===== NAVIGATION =====
  navHome: { en: "Home", ku: "ماڵەوە", ar: "الرئيسية" },
  navDatabase: { en: "Database", ku: "بنکەدراوە", ar: "قاعدة البيانات" },
  navResearch: { en: "Research Library", ku: "کتێبخانەی توێژینەوە", ar: "مكتبة الأبحاث" },
  navSources: { en: "Sources", ku: "سەرچاوەکان", ar: "المصادر" },
  navHowItWorks: { en: "How It Works", ku: "چۆن کاردەکات", ar: "كيف يعمل" },
  navAbout: { en: "About", ku: "دەربارە", ar: "حول" },
  navGetNotified: { en: "Get Notified", ku: "ئاگادار ببە", ar: "احصل على إشعار" },

  // ===== FOOTER =====
  footerTagline: {
    en: "A community-driven research initiative cross-referencing Kurdistan market product ingredients against international scientific and regulatory databases.", 
    ku: "هەوڵدانێکی توێژینەوەی بنەما-کۆمەڵگاییە کە پێکهاتەکانی بەرهەمەکانی بازاڕی کوردستان بە بنکەدراوە زانستی و ڕێکخستنە نێودەوڵەتییەکان لێک دەکاتەوە.", 
    ar: "مبادرة بحثية مجتمعية تقارن مكونات منتجات أسواق كردستان بقواعد البيانات العلمية والتنظيمية الدولية.",
  },
  footerColPlatform: { en: "Platform", ku: "پلاتفۆرم", ar: "المنصة" },
  footerColResources: { en: "Resources", ku: "سەرچاوەکان", ar: "الموارد" },
  footerColLegal: { en: "Legal", ku: "یاسایی", ar: "قانوني" },
  footerLinkScientificSources: {
    en: "Scientific Sources", ku: "سەرچاوە زانستییەکان", ar: "المصادر العلمية",
  },
  footerLinkReportError: {
    en: "Report Error", ku: "ڕاپۆرتکردنی هەڵە", ar: "الإبلاغ عن خطأ",
  },
  footerLinkPrivacy: {
    en: "Privacy Policy", ku: "سیاسەتی تایبەتمەندی", ar: "سياسة الخصوصية",
  },
  footerLinkTerms: {
    en: "Terms of Service", ku: "مەرجەکانی خزمەتگوزاری", ar: "شروط الخدمة",
  },
  footerCompliance: {
    en: "Hêja supports Consumer Protection Law No. 1 of 2010 guaranteeing Iraqi citizens the right to accurate product information. We are an independent community transparency initiative not affiliated with any government body, regulatory agency, brand, or commercial entity.", 
    ku: "هێژا پشتیوانی لە یاسای ژمارە ١ ی ساڵی ٢٠١٠ ی پاراستنی بەکاربەر دەکات کە مافی هاوڵاتیانی عێراق دەستەبەر دەکات بۆ وەرگرتنی زانیاری ورد دەربارەی بەرهەمەکان. ئێمە دەستپێشخەرییەکی سەربەخۆی ڕوونیی کۆمەڵگاین و پەیوەندیمان بە هیچ دەستەیەکی حکومی، دەزگایەکی ڕێکخستن، براند، یان دەزگایەکی بازرگانییەوە نییە.", 
    ar: "تدعم هيجا قانون حماية المستهلك رقم 1 لسنة 2010 الذي يضمن حق المواطنين العراقيين في الحصول على معلومات دقيقة عن المنتجات. نحن مبادرة شفافية مجتمعية مستقلة وغير منتسبين لأي جهة حكومية أو تنظيمية أو علامة تجارية أو كيان تجاري.",
  },
  footerCopyright: {
    en: "© 2026 Hêja Community Research Project", ku: "© ٢٠٢٦ پڕۆژەی توێژینەوەی کۆمەڵگای هێژا", ar: "© 2026 مشروع هيجا البحثي المجتمعي",
  },

  // ===== DATABASE PAGE =====
  dbEyebrow: { en: "Open Database", ku: "بنکەدراوەی کراوە", ar: "قاعدة البيانات المفتوحة" },
  dbTitle: {
    en: "Kurdistan Market Ingredient Database", ku: "بنکەدراوەی پێکهاتەکانی بازاڕی کوردستان", ar: "قاعدة بيانات مكونات أسواق كردستان",
  },
  dbSubtitle: {
    en: "{count} products cross-referenced against international scientific databases. Updated regularly.", ku: "{count} بەرهەم لێکدراونەتەوە بە بنکەدراوە زانستییە نێودەوڵەتییەکان. بە بەردەوامی نوێ دەکرێتەوە.", ar: "{count} منتج تم مطابقة مكوناتها مع قواعد بيانات علمية دولية، يتم التحديث باستمرار." },
  dbNotice: {
    en: "Research flags indicate that an ingredient appears in scientific literature or regulatory databases. A flag does not mean a product is unsafe. It means published research exists about that ingredient. Click any ingredient to read the original source.", 
    ku: "ئاماژەکانی توێژینەوە ئەوە دەردەخەن کە پێکهاتەیەک لە نووسراوە زانستی یان بنکەدراوە ڕێکخستنییەکاندا دەردەکەوێت. ئاماژەیەک مانای ئەوە نییە کە بەرهەمەکە نادروستە. مانای ئەوەیە توێژینەوەی بڵاوکراوە هەیە سەبارەت بەو پێکهاتەیە. کلیک لە هەر پێکهاتەیەک بکە بۆ خوێندنەوەی سەرچاوەی ڕەسەن.", 
    ar: "تشير إشارات الأبحاث إلى أن المكون يظهر في المؤلفات العلمية أو قواعد البيانات التنظيمية. هذه الإشارة لا تعني أن المنتج غير آمن، بل تعني أن هناك أبحاثًا منشورة حول هذا المكون. انقر فوق أي مكون لقراءة المصدر الأصلي." },
  dbSearchPlaceholder: {
    en: "Search {count} Kurdistan market products...", ku: "لە {count} بەرهەمی بازاڕی کوردستاندا بگەڕێ...", ar: "ابحث في {count} منتج من أسواق كردستان..." },
  dbSortHighest: { en: "Highest Score", ku: "بەرزترین نمرە", ar: "الأعلى تقييماً" },
  dbSortLowest: { en: "Lowest Score", ku: "نزمترین نمرە", ar: "الأقل تقييماً" },
  dbSortCategory: { en: "Category", ku: "جۆر", ar: "الفئة" },
  dbSortRecent: { en: "Recently Added", ku: "بەم دواییە زیادکراوە", ar: "المضافة حديثاً" },

  dbFilterAll: { en: "All", ku: "هەموو", ar: "الكل" },
  dbFilterLow: { en: "Low Research Flags", ku: "ئاماژەی توێژینەوەی کەم", ar: "إشارات بحث منخفضة" },
  dbFilterMod: { en: "Moderate Research Flags", ku: "ئاماژەی توێژینەوەی مامناوەند", ar: "إشارات بحث متوسطة" },
  dbFilterHigh: { en: "High Research Flags", ku: "ئاماژەی توێژینەوەی زۆر", ar: "إشارات بحث عالية" },

  dbShowingPrefix: { en: "Showing", ku: "پیشاندانی", ar: "يتم عرض" },
  dbProductSingular: { en: "product", ku: "بەرهەم", ar: "منتج" },
  dbProductPlural: { en: "products", ku: "بەرهەم", ar: "منتجات" },
  dbMatching: { en: "matching", ku: "گونجاو لەگەڵ", ar: "مطابق" },
  dbEmpty: { en: "No products match your filters.", ku: "هیچ بەرهەمێک لەگەڵ پاڵاوتنەکانت ناگونجێت.", ar: "لا توجد منتجات تطابق الفلاتر المحددة." },

  // ===== FLAG PILL LABELS =====
  flagLowLabel: { en: "LOW RESEARCH FLAGS", ku: "ئاماژەی توێژینەوەی کەم", ar: "إشارات بحث منخفضة" },
  flagModLabel: { en: "MODERATE RESEARCH FLAGS", ku: "ئاماژەی توێژینەوەی مامناوەند", ar: "إشارات بحث متوسطة" },
  flagHighLabel: { en: "HIGH RESEARCH FLAGS", ku: "ئاماژەی توێژینەوەی زۆر", ar: "إشارات بحث عالية" },

  // ===== PRODUCT CARD =====
  pcAiBadge: { en: "AI-Estimated", ku: "خەمڵێنراوی زیرەکی دەستکرد", ar: "مقدر بالذكاء الاصطناعي" },
  pcDbBadge: { en: "DB Verified", ku: "لە بنکەدراوە پشتڕاستکراوە", ar: "مُحقق بقاعدة البيانات" },
  pcAiTitle: {
    en: "Generated using ChatGPT AI. Not manually verified.", ku: "بە یارمەتی ChatGPT دروست کراوە. بە دەست پشتڕاست نەکراوە.", ar: "تم التوليد باستخدام ChatGPT. لم يتم التحقق منه يدوياً." },
  pcPrimaryFlagged: { en: "Primary flagged substance", ku: "سەرەکیترین ماددەی ئاماژەپێکراو", ar: "المادة الأساسية الموسومة" },
  pcViewResearch: { en: "View Research", ku: "توێژینەوە ببینە", ar: "عرض الأبحاث" },

  // ===== PRODUCT DETAIL MODAL =====
  pdClose: { en: "Close", ku: "داخستن", ar: "إغلاق" },
  pdAiMayError: {
    en: "AI-Estimated · May Contain Errors", ku: "خەمڵێنراوی زیرەکی دەستکرد · لەوانەیە هەڵەی تێدا بێت", ar: "مقدر بالذكاء الاصطناعي · قد يحتوي على أخطاء" },
  pdDbVerified: { en: "Database Verified", ku: "لە بنکەدراوە پشتڕاستکراوە", ar: "تم التحقق منه بقاعدة البيانات" },
  pdAiDisclosure: { en: "AI Disclosure:", ku: "ڕاگەیاندنی زیرەکی دەستکرد:", ar: "الإفصاح عن استخدام الذكاء الاصطناعي:" },
  pdFlaggedTitle: { en: "Flagged in Literature", ku: "لە نووسراوە زانستیەکاندا ئاماژەی پێکراوە", ar: "مذكور في المؤلفات كتحذير" },
  pdSafeTitle: { en: "Unflagged Ingredients", ku: "پێکهاتە ئاماژە-نەکراوەکان", ar: "مكونات غير موسومة" },
  pdSummaryTitle: { en: "Summary", ku: "پوختە", ar: "ملخص" },
  pdRecTitle: {
    en: "Database cross-reference suggests", ku: "لێکدانەوەی بنکەدراوە پێشنیار دەکات", ar: "التقاطع المرجعي لقاعدة البيانات يقترح" },
  pdAltTitle: {
    en: "Research suggests considering", ku: "توێژینەوە پێشنیار دەکات سەیری ئەمە بکەیت", ar: "الأبحاث تقترح الأخذ بعين الاعتبار" },
  pdDataSource: { en: "Data source:", ku: "سەرچاوەی داتا:", ar: "مصدر البيانات:" },

  // ===== CATEGORY NAMES (backend strings → translated labels) =====
  "category.Baby Care": { en: "Baby Care", ku: "چاودێری منداڵ", ar: "رعاية الطفل" },
  "category.COMING SOON - Traditional Foods": {
    en: "COMING SOON - Traditional Foods", ku: "بەمزوانە - خواردنە نەریتیەکان", ar: "قريباً - أطعمة تقليدية" },
  "category.Food - Beverages": { en: "Food - Beverages", ku: "خواردن - خواردنەوەکان", ar: "طعام - مشروبات" },
  "category.Food - Cooking Oils": { en: "Food - Cooking Oils", ku: "خواردن - ڕۆنی لێنان", ar: "طعام - زيوت الطبخ" },
  "category.Food - Dairy": { en: "Food - Dairy", ku: "خواردن - بەرهەمی شیرەمەنی", ar: "طعام - منتجات الألبان" },
  "category.Food - Dairy and Eggs": {
    en: "Food - Dairy and Eggs", ku: "خواردن - شیرەمەنی و هێلکە", ar: "طعام - منتجات الألبان والبيض" },
  "category.Food - Fruits and Snacks": {
    en: "Food - Fruits and Snacks", ku: "خواردن - میوە و خواردنی سووک", ar: "طعام - فواكه ووجبات خفيفة" },
  "category.Food - Snacks": { en: "Food - Snacks", ku: "خواردن - خواردنی سووک", ar: "طعام - وجبات خفيفة" },
  "category.Food - Spices": { en: "Food - Spices", ku: "خواردن - بەهارات", ar: "طعام - بهارات" },
  "category.Food - Staples": { en: "Food - Staples", ku: "خواردن - سەرەکییەکان", ar: "طعام - الأساسيات" },
  "category.Household Cleaning": {
    en: "Household Cleaning", ku: "پاککردنەوەی ماڵەوە", ar: "تنظيف المنزل" },
  "category.Laundry": { en: "Laundry", ku: "جلشۆردن", ar: "غسيل الملابس" },
  "category.Oral Care": { en: "Oral Care", ku: "چاودێری دەم و ددان", ar: "العناية بالفم" },
  "category.Personal Care - Baby": {
    en: "Personal Care - Baby", ku: "چاودێری کەسی - منداڵ", ar: "العناية الشخصية - للأطفال" },
  "category.Personal Care - Grooming": {
    en: "Personal Care - Grooming", ku: "چاودێری کەسی - ڕازاندنەوە", ar: "العناية الشخصية - التجميل" },
  "category.Personal Care - Hair": {
    en: "Personal Care - Hair", ku: "چاودێری کەسی - قژ", ar: "العناية الشخصية - للشعر" },
  "category.Personal Care - Skincare": {
    en: "Personal Care - Skincare", ku: "چاودێری کەسی - چاودێری پێست", ar: "العناية الشخصية - بالبشرة" },

  // ===== Not Found =====
  nfTitle: { en: "Page not found", ku: "پەڕە نەدۆزرایەوە", ar: "الصفحة غير موجودة" },
  nfSub: { 
    en: "The page you're looking for has moved or never existed.", 
    ku: "ئەو پەڕەیەی بەدوایدا دەگەڕێیت گواستراوەتەوە یان هەرگیز بوونی نەبووە.", 
    ar: "الصفحة التي تبحث عنها تم نقلها أو لم تكن موجودة أبداً." 
  },
  nfBtn: { en: "Back to home", ku: "گەڕانەوە بۆ ماڵەوە", ar: "العودة للرئيسية" },
};

export function LangProvider({ children }) {
  const [lang, setLangState] = useState("en");

  useEffect(() => {
    const saved = localStorage.getItem(STORE_KEY);
    if (saved && LANGS[saved]) setLangState(saved);
  }, []);

  const setLang = (code) => {
    if (!LANGS[code]) return;
    setLangState(code);
    localStorage.setItem(STORE_KEY, code);
  };

  const value = useMemo(
    () => ({
      lang,
      setLang,
      dir: LANGS[lang].dir,
      t: (key) => TRANSLATIONS[key]?.[lang] ?? TRANSLATIONS[key]?.en ?? "",
    }),
    [lang]
  );

  return <LangContext.Provider value={value}>{children}</LangContext.Provider>;
}

export const useLang = () => {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error("useLang must be used within LangProvider");
  return ctx;
};
